version: '3.8'
services:
  app:
    build: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/rubilnik
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - HIBERNATE_SHOW_SQL=true
      - HIBERNATE_HBM2DDL_AUTO=create # update # create
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=rubilnik
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

#TODO